
CREATE TABLE IF NOT EXISTS USERS_PROFILE(
    ID          UUID            PRIMARY KEY,
    USERNAME    VARCHAR(30),
    EMAIL       VARCHAR(255)    UNIQUE,
    PWD         VARCHAR(72),
    CREATED_AT  TIMESTAMP,
    EDITED_AT   TIMESTAMP,
    VERIFIED    VARCHAR
);

CREATE TABLE IF NOT EXISTS LANGUAGES(
    ISO         VARCHAR(2)      PRIMARY KEY,
    LANG        VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS WORDS(
    WORD        VARCHAR(50)     PRIMARY KEY,
    UNIT        VARCHAR(8),        
    LANG_ISO    VARCHAR(2)      REFERENCES LANGUAGES(ISO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CONTENTS_HEAD(
    ID          UUID            PRIMARY KEY,
    USER_ID     UUID            REFERENCES USERS_PROFILE(ID) ON DELETE CASCADE,
    TITLE       VARCHAR(255),
    LANG_ISO    VARCHAR(20)     REFERENCES LANGUAGES(ISO),
    CREATED_AT  TIMESTAMP,
    EDITED_AT   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONTENTS_BODY(
    ID          UUID,
    HEAD_ID     UUID            REFERENCES CONTENTS_HEAD(ID) ON DELETE CASCADE,
    BODY        TEXT,
    CREATED_AT  TIMESTAMP,
    EDITED_AT   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STUDY_OVERVIEW(
    USER_ID     UUID            REFERENCES USERS_PROFILE(ID) ON DELETE CASCADE,
    LANG_ISO    VARCHAR(2)      REFERENCES LANGUAGES(ISO) ON DELETE CASCADE,
    WORD        VARCHAR(50)     REFERENCES WORDS(WORD) ON DELETE CASCADE,
    LITERACY    INT             
);

CREATE TABLE IF NOT EXISTS INVENTORY(
    USER_ID     UUID            REFERENCES USERS_PROFILE(ID) ON DELETE CASCADE,
    HEAD_ID     UUID            REFERENCES CONTENTS_HEAD(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NOTE(
    USER_ID     UUID            REFERENCES USERS_PROFILE(ID) ON DELETE CASCADE,
    WORD        VARCHAR(50)     REFERENCES WORDS(WORD) ON DELETE CASCADE,
    NOTE        VARCHAR(255)
);