CREATE DATABASE lingo;
\c lingo;

CREATE TABLE users (
    id VARCHAR PRIMARY KEY NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    pwd VARCHAR(255) NOT NULL
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

